export const ALBUMREQ = "ALBUMREQ";
export const ALBUMSUC = "ALBUMSUC";
export const ALBUMREJ = "ALBUMREJ";

export const SINGLEDATAREQ = 'SINGLEDATAREQ';
export const SINGLEDATARES = 'SINGLEDATARES';
export const SINGLEDATAREJ = 'SINGLEDATAREJ';

export const EDITDATAREQ = "EDITDATAREQ";
export const EDITDATAREJ ="EDITDATAREj";

export const DELETEDATAREQ ="DELETEDATAREQ";
export const DELETEDATAREJ ="DELETEDATAREJ";

export const SIGNUPREQ ="SIGNUPREQ";
export const SIGNUPRES ="SIGNUPRES";
export const SIGNUPREJ ="SIGNUPREJ";
export const SIGNINREQ ="SIGNINREQ";
export const SIGNINRES ="SIGNINRES";
export const SIGNINREJ ="SIGNINREJ";
export const SIGNOUTREQ ="SIGNOUTREQ";
export const SIGNOUTRES ="SIGNOUTRES";
export const SIGNOUTREJ ="SIGNOUTREJ";

export const GOOGLESIGNINREQ ="GOOGLESIGNINREQ";
export const GOOGLESIGNINRES ="GOOGLESIGNINRES";
export const GOOGLESIGNINREJ ="GOOGLESIGNINREJ";